name: BedWarsHub
author: QuadrixYT & quele
version: 1.0
api-version: 1.16
depend:
  - CloudNet-Bridge
main: eu.hypetime.spigot.bedwarshub.BedWarsHub

commands:
  set:
    description: Set Location Command